.TH mdconv "1" "August 2021" "Palexer, Version 0.95"
.SH NAME
mdconv

.SH DESCRIPTION

.LP
mdconv can be used to convert Markdown documents to PDF or HTML.

.SH OVERVIEW
.B mdconv 
[OPTIONS]... [FILE]

.SH OPTIONS
.LP
.B -o outputfile.ext

.IP 
Specify the output file name and file type. Replace 'ext' with either 'pdf' or 'html' to use the corresponding formats.

.LP
.B -css [PATH]

.IP 
Specify a custom CSS stylesheet.

.LP
.B -overwrite

.IP 
If the -overwrite flag is parsed, the default style sheet is not included in the output file.

.LP
.B -grayscale

.IP
Make the PDF output grayscale only

.LP
.B -h, -help

.IP 
Get general usage information

.LP
.B -margin-left [SIZE], -margin-right [SIZE], -margin-top [SIZE], -margin-bottom [SIZE]

.IP
Specify the margins of the page (left, right, top, bottom) in mm.

.LP
.B -dpi [VALUE]

.IP
Specify the DPI of the PDF document.

.LP
.B -size [VALUE]

.IP
Specify the size of the output document (default A4).
Available options: letter, legal, a1, a2, a3, a4, a5, a6

.LP
.B -orientation [VALUE]

.IP
Specify the orientation of the output document (portrait (default) or landscape).


.LP
.B -v, -V

.IP
Print currently used mdconv version

.LP
See also 'mdconv -h' for more information.

.SH AUTHOR
.TP 2
Palexer
